### ISSUE TITLE
Help with installation and Makefile

### ISSUE THREAD

**Issue by SRkumar97** [ucns3d-team/UCNS3D#46]
Hello!
I am trying to install the manual version of the code, with the use of GFortran parallel and OpenBLAS library for Ubuntu 20.04.

I first compiled OpenBLAS. 

After downloading the full code and opening terminal in the src folder of the code, it is said that we should type 

make -f Makefile_common clean all 

However make reports that there is no Makefile, and stops. So I type the following command for the Makefile_common. 

make -f Makefile_common clean all

![image](https://user-images.githubusercontent.com/109019272/236296388-5170a2a7-0fd1-483b-b220-702a23fa022d.png)

I am facing issue with the Makefile. The output shows error for every line of the Makefile_common. Did I miss something? Do I need to set paths for OpenBLAS, anywhere within the Makefile?

Thanks a ton

**Comment by sidkamat** [comment]
You need to copy the Makefile from the "bin" folder and use that to compile the code

**Comment by SRkumar97** [comment]
Thanks @ sidkamat, got it.

I did this, copied the Malefile from UCNS3D > bin > gnu-compiler to the UCNS3D > src folder

Once I begin the process again, the make command now works, but gets stuck at a point due to an error related to **grid_t.o**

----------------------------------------------------------
    code:
    ASSIGN transform:vvb(1:3_8) transform:vext(1 , 1:3_8)
    ASSIGN transform:vvc(1:3_8) transform:vext(2 , 1:3_8)
    ASSIGN transform:vvd(1:3_8) transform:vext(3 , 1:3_8)
    ASSIGN transform:vva(1 , 1) transform:vvb(2)
    ASSIGN transform:vva(2 , 1) transform:vvc(2)
    ASSIGN transform:vva(3 , 1) transform:vvd(2)
    ASSIGN transform:vva(1 , 2) transform:vvb(3)
    ASSIGN transform:vva(2 , 2) transform:vvc(3)
    ASSIGN transform:vva(3 , 2) transform:vvd(3)
    ASSIGN transform:vva(1 , 3) 1.0000000000000000
    ASSIGN transform:vva(2 , 3) 1.0000000000000000
    ASSIGN transform:vva(3 , 3) 1.0000000000000000
    ASSIGN transform:vvjacobsurf(1) (+ (- (* transform:vva(1 , 1) (parens (- (parens (* transform:vva(3 , 3) transform:vva(2 , 2))) (parens (* transform:vva(3 , 2) transform:vva(2 , 3)))))) (* transform:vva(2 , 1) (parens (- (parens (* transform:vva(3 , 3) transform:vva(1 , 2))) (parens (* transform:vva(3 , 2) transform:vva(1 , 3))))))) (* transform:vva(3 , 1) (parens (- (parens (* transform:vva(2 , 3) transform:vva(1 , 2))) (parens (* transform:vva(2 , 2) transform:vva(1 , 3)))))))
    ASSIGN transform:vva(1 , 1) transform:vvb(3)
    ASSIGN transform:vva(2 , 1) transform:vvc(3)
    ASSIGN transform:vva(3 , 1) transform:vvd(3)
    ASSIGN transform:vva(1 , 2) transform:vvb(1)
    ASSIGN transform:vva(2 , 2) transform:vvc(1)
    ASSIGN transform:vva(3 , 2) transform:vvd(1)
    ASSIGN transform:vva(1 , 3) 1.0000000000000000
    ASSIGN transform:vva(2 , 3) 1.0000000000000000
    ASSIGN transform:vva(3 , 3) 1.0000000000000000
    ASSIGN transform:vvjacobsurf(2) (+ (- (* transform:vva(1 , 1) (parens (- (parens (* transform:vva(3 , 3) transform:vva(2 , 2))) (parens (* transform:vva(3 , 2) transform:vva(2 , 3)))))) (* transform:vva(2 , 1) (parens (- (parens (* transform:vva(3 , 3) transform:vva(1 , 2))) (parens (* transform:vva(3 , 2) transform:vva(1 , 3))))))) (* transform:vva(3 , 1) (parens (- (parens (* transform:vva(2 , 3) transform:vva(1 , 2))) (parens (* transform:vva(2 , 2) transform:vva(1 , 3)))))))
    ASSIGN transform:vva(1 , 1) transform:vvb(1)
    ASSIGN transform:vva(2 , 1) transform:vvc(1)
    ASSIGN transform:vva(3 , 1) transform:vvd(1)
    ASSIGN transform:vva(1 , 2) transform:vvb(2)
    ASSIGN transform:vva(2 , 2) transform:vvc(2)
    ASSIGN transform:vva(3 , 2) transform:vvd(2)
    ASSIGN transform:vva(1 , 3) 1.0000000000000000
    ASSIGN transform:vva(2 , 3) 1.0000000000000000
    ASSIGN transform:vva(3 , 3) 1.0000000000000000
    ASSIGN transform:vvjacobsurf(3) (+ (- (* transform:vva(1 , 1) (parens (- (parens (* transform:vva(3 , 3) transform:vva(2 , 2))) (parens (* transform:vva(3 , 2) transform:vva(2 , 3)))))) (* transform:vva(2 , 1) (parens (- (parens (* transform:vva(3 , 3) transform:vva(1 , 2))) (parens (* transform:vva(3 , 2) transform:vva(1 , 3))))))) (* transform:vva(3 , 1) (parens (- (parens (* transform:vva(2 , 3) transform:vva(1 , 2))) (parens (* transform:vva(2 , 2) transform:vva(1 , 3)))))))
    ASSIGN transform:trianglearea (parens (* (parens transform:oo2) (parens __sqrt_r8[[(((+ (+ (parens (** transform:vvjacobsurf(1) 2)) (parens (** transform:vvjacobsurf(2) 2))) (parens (** transform:vvjacobsurf(3) 2)))))]])))
    

make: *** [Makefile_common:59: grid_t.o] Error 1

-----------------------------------------------------------
Is this error common?

**Comment by VadimCRN** [comment]
Hello, make sure both the makefile and makefile_common files are in the code directory and compile with "make -f Makefile clean all"

________________________________
Da: SRkumar97 ***@***.***>
Inviato: venerdì 5 maggio 2023 08:17
A: ucns3d-team/UCNS3D ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: Re: [ucns3d-team/UCNS3D] Help with installation and Makefile (Issue #46)


Thanks @ sidkamat, got it.

I did this, copied the Malefile from UCNS3D > bin > gnu-compiler to the UCNS3D > src folder

Once I begin the process again, the make command now works, but gets stuck at a point due to an error related to grid_t.o

________________________________

code:
ASSIGN transform:vvb(1:3_8) transform:vext(1 , 1:3_8)
ASSIGN transform:vvc(1:3_8) transform:vext(2 , 1:3_8)
ASSIGN transform:vvd(1:3_8) transform:vext(3 , 1:3_8)
ASSIGN transform:vva(1 , 1) transform:vvb(2)
ASSIGN transform:vva(2 , 1) transform:vvc(2)
ASSIGN transform:vva(3 , 1) transform:vvd(2)
ASSIGN transform:vva(1 , 2) transform:vvb(3)
ASSIGN transform:vva(2 , 2) transform:vvc(3)
ASSIGN transform:vva(3 , 2) transform:vvd(3)
ASSIGN transform:vva(1 , 3) 1.0000000000000000
ASSIGN transform:vva(2 , 3) 1.0000000000000000
ASSIGN transform:vva(3 , 3) 1.0000000000000000
ASSIGN transform:vvjacobsurf(1) (+ (- (* transform:vva(1 , 1) (parens (- (parens (* transform:vva(3 , 3) transform:vva(2 , 2))) (parens (* transform:vva(3 , 2) transform:vva(2 , 3)))))) (* transform:vva(2 , 1) (parens (- (parens (* transform:vva(3 , 3) transform:vva(1 , 2))) (parens (* transform:vva(3 , 2) transform:vva(1 , 3))))))) (* transform:vva(3 , 1) (parens (- (parens (* transform:vva(2 , 3) transform:vva(1 , 2))) (parens (* transform:vva(2 , 2) transform:vva(1 , 3)))))))
ASSIGN transform:vva(1 , 1) transform:vvb(3)
ASSIGN transform:vva(2 , 1) transform:vvc(3)
ASSIGN transform:vva(3 , 1) transform:vvd(3)
ASSIGN transform:vva(1 , 2) transform:vvb(1)
ASSIGN transform:vva(2 , 2) transform:vvc(1)
ASSIGN transform:vva(3 , 2) transform:vvd(1)
ASSIGN transform:vva(1 , 3) 1.0000000000000000
ASSIGN transform:vva(2 , 3) 1.0000000000000000
ASSIGN transform:vva(3 , 3) 1.0000000000000000
ASSIGN transform:vvjacobsurf(2) (+ (- (* transform:vva(1 , 1) (parens (- (parens (* transform:vva(3 , 3) transform:vva(2 , 2))) (parens (* transform:vva(3 , 2) transform:vva(2 , 3)))))) (* transform:vva(2 , 1) (parens (- (parens (* transform:vva(3 , 3) transform:vva(1 , 2))) (parens (* transform:vva(3 , 2) transform:vva(1 , 3))))))) (* transform:vva(3 , 1) (parens (- (parens (* transform:vva(2 , 3) transform:vva(1 , 2))) (parens (* transform:vva(2 , 2) transform:vva(1 , 3)))))))
ASSIGN transform:vva(1 , 1) transform:vvb(1)
ASSIGN transform:vva(2 , 1) transform:vvc(1)
ASSIGN transform:vva(3 , 1) transform:vvd(1)
ASSIGN transform:vva(1 , 2) transform:vvb(2)
ASSIGN transform:vva(2 , 2) transform:vvc(2)
ASSIGN transform:vva(3 , 2) transform:vvd(2)
ASSIGN transform:vva(1 , 3) 1.0000000000000000
ASSIGN transform:vva(2 , 3) 1.0000000000000000
ASSIGN transform:vva(3 , 3) 1.0000000000000000
ASSIGN transform:vvjacobsurf(3) (+ (- (* transform:vva(1 , 1) (parens (- (parens (* transform:vva(3 , 3) transform:vva(2 , 2))) (parens (* transform:vva(3 , 2) transform:vva(2 , 3)))))) (* transform:vva(2 , 1) (parens (- (parens (* transform:vva(3 , 3) transform:vva(1 , 2))) (parens (* transform:vva(3 , 2) transform:vva(1 , 3))))))) (* transform:vva(3 , 1) (parens (- (parens (* transform:vva(2 , 3) transform:vva(1 , 2))) (parens (* transform:vva(2 , 2) transform:vva(1 , 3)))))))
ASSIGN transform:trianglearea (parens (* (parens transform:oo2) (parens __sqrt_r8[[(((+ (+ (parens (** transform:vvjacobsurf(1) 2)) (parens (** transform:vvjacobsurf(2) 2))) (parens (** transform:vvjacobsurf(3) 2)))))]])))


make: *** [Makefile_common:59: grid_t.o] Error 1

________________________________

Is this error common?

**Comment by SRkumar97** [comment]
@VadimCRN Thanks, that's how I tried - copied Makefile to the src directory as written in the instructions (there is no directory called "code"). Makefile_common is also in the src folder only. 
But the error related to **grid_t.o** appears, as shown in the image above.

**Comment by SRkumar97** [comment]
@sidkamat could you please let me know how you installed the code? I'm trying with OpenBLAS and GFortran MPI, but can't understand what is the issue with grid_t.F90, that the object file error appears while trying to make.

**Comment by SRkumar97** [comment]
Thank you for this, I will do this way and get back.

**Comment by SRkumar97** [comment]
Thanks a ton, now the ucns3d_p exectuable has been built successfully. In the src folder wherein the Makefile command was run.

**Comment by SRkumar97** [comment]
Hello! I am trying to run the Taylor Green Vortex testcase, provided in the tests directory. I copied the executable ucns3d_p to the test folder and initiated the parallel run using 8 procs for the case -
![error_run](https://github.com/ucns3d-team/UCNS3D/assets/109019272/51c48279-bd63-4bcb-b3a9-f6d0832d1bbb)

The case runs for a few minutes, writes 6-7 restart.dat files but suddenyl terminates by itself with the error message(s) as shown in the attached PNG. Request for your help.

**Comment by SRkumar97** [comment]
The issue gets sorted if I use ulimit -s unlimited before running the case.
